# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import TemperatureService_pb2 as TemperatureService__pb2


class TemperatureSensorServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetTemperature = channel.unary_unary(
        '/temperatureSensorService.TemperatureSensorService/GetTemperature',
        request_serializer=TemperatureService__pb2.TemperatureRequest.SerializeToString,
        response_deserializer=TemperatureService__pb2.TemperatureReply.FromString,
        )


class TemperatureSensorServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetTemperature(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TemperatureSensorServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetTemperature': grpc.unary_unary_rpc_method_handler(
          servicer.GetTemperature,
          request_deserializer=TemperatureService__pb2.TemperatureRequest.FromString,
          response_serializer=TemperatureService__pb2.TemperatureReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'temperatureSensorService.TemperatureSensorService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
