# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TemperatureService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TemperatureService.proto',
  package='temperatureSensorService',
  syntax='proto3',
  serialized_options=_b('\n\010grpc.tssB\035TemperatureSensorServiceProtoP\001\242\002\003TSS'),
  serialized_pb=_b('\n\x18TemperatureService.proto\x12\x18temperatureSensorService\"&\n\x12TemperatureRequest\x12\x10\n\x08sensorId\x18\x01 \x01(\x05\"\'\n\x10TemperatureReply\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x32\x88\x01\n\x18TemperatureSensorService\x12l\n\x0eGetTemperature\x12,.temperatureSensorService.TemperatureRequest\x1a*.temperatureSensorService.TemperatureReply\"\x00\x42\x31\n\x08grpc.tssB\x1dTemperatureSensorServiceProtoP\x01\xa2\x02\x03TSSb\x06proto3')
)




_TEMPERATUREREQUEST = _descriptor.Descriptor(
  name='TemperatureRequest',
  full_name='temperatureSensorService.TemperatureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensorId', full_name='temperatureSensorService.TemperatureRequest.sensorId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=92,
)


_TEMPERATUREREPLY = _descriptor.Descriptor(
  name='TemperatureReply',
  full_name='temperatureSensorService.TemperatureReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='temperatureSensorService.TemperatureReply.temperature', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['TemperatureRequest'] = _TEMPERATUREREQUEST
DESCRIPTOR.message_types_by_name['TemperatureReply'] = _TEMPERATUREREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TemperatureRequest = _reflection.GeneratedProtocolMessageType('TemperatureRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATUREREQUEST,
  '__module__' : 'TemperatureService_pb2'
  # @@protoc_insertion_point(class_scope:temperatureSensorService.TemperatureRequest)
  })
_sym_db.RegisterMessage(TemperatureRequest)

TemperatureReply = _reflection.GeneratedProtocolMessageType('TemperatureReply', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATUREREPLY,
  '__module__' : 'TemperatureService_pb2'
  # @@protoc_insertion_point(class_scope:temperatureSensorService.TemperatureReply)
  })
_sym_db.RegisterMessage(TemperatureReply)


DESCRIPTOR._options = None

_TEMPERATURESENSORSERVICE = _descriptor.ServiceDescriptor(
  name='TemperatureSensorService',
  full_name='temperatureSensorService.TemperatureSensorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=136,
  serialized_end=272,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTemperature',
    full_name='temperatureSensorService.TemperatureSensorService.GetTemperature',
    index=0,
    containing_service=None,
    input_type=_TEMPERATUREREQUEST,
    output_type=_TEMPERATUREREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEMPERATURESENSORSERVICE)

DESCRIPTOR.services_by_name['TemperatureSensorService'] = _TEMPERATURESENSORSERVICE

# @@protoc_insertion_point(module_scope)
